# These are supported funding model platforms

github: ['kennedy-ex', 'riz-ex', 'aryazakaria01', 'FeriEXP']
community_bridge: Ribaj Osmani 
custom: ['https://t.me/osmanigroupbot', 'https://t.me/osmanibots']
